Repository RedHatQE/wrapanapi, pull requests merged in 2018-05, with the labels that each got.

#249 [1LP][RFR] fix of issue when pod appliances are sometimes not removed
  wrapanapi/containers/providers/rhopenshift.py
Labels: enhancement, lint-ok

#248 [1LP][RFR]added list_region
  wrapanapi/msazure.py
Labels: lint-ok

#247 [RFR] Option to verify IPv4 when getting VM's IP address from RHV
  wrapanapi/rhevm.py
Labels: lint-ok

#234 [1LP][RFR] ovirtsdk v4 update
  requirements.txt
  wrapanapi/exceptions.py
  wrapanapi/rhevm.py
Labels: enhancement, lint-ok

#250 [1LP][RFR] Reimplement list_servers and fix get_server_memory in lenovo.py
  wrapanapi/lenovo.py
Labels: enhancement, lint-ok

#253 [1LP][RFR] added retry functionality in order to sort out Unathorized error in sprout
  wrapanapi/containers/providers/rhopenshift.py
Labels: lint-ok

#256 [1LP][RFR] no enum34 on python3 needed
  requirements-test.txt
  requirements.txt
Labels: lint-ok

#257 [1LP][RFR] added get_ip_address method for compatibility
  wrapanapi/containers/providers/rhopenshift.py
Labels: enhancement, lint-ok

#252 [1LP][RFR] Add network and storage device support to LenovoSystem
  wrapanapi/lenovo.py
Labels: enhancement, lint-ok

#258 [RFR] changed default version to 5.9
  wrapanapi/containers/providers/rhopenshift.py
Labels: enhancement, lint-ok

#262 [1LP][RFR]fix rhevm.mark_as_template, need Vm not VmService
  wrapanapi/rhevm.py
Labels: bug

#263 [RFR] Added new methods to RHEVMSystem
  wrapanapi/rhevm.py
Labels: lint-ok

#260 [1LP][RFR]fix to avoid new nic removal
  wrapanapi/msazure.py
Labels: lint-ok
