Repository RedHatQE/wrapanapi, pull requests merged in 2018-02, with the labels that each got.

#210 [RFR] Deploy podified CFME changes (for sprout)
  requirements.txt
  tests/test_openshift.py
  wrapanapi/__init__.py
  wrapanapi/containers/providers/openshift.py
  wrapanapi/containers/providers/rhkubernetes.py
  wrapanapi/containers/providers/rhopenshift.py
Labels: lint-ok

#211 [RFR] Fix list_services and list_container_groups
  wrapanapi/containers/providers/rhkubernetes.py
Labels: lint-ok

#215 Update azure version to >=3.0.0
  requirements.txt
Labels: bug, lint-ok

#212 [RFR] Scvmm tests + port to xlml.fromstring
  .gitignore
  requirements-test.txt
  tests/test_scvmm.py
  wrapanapi/scvmm.py
Labels: lint-ok

#214 [RFR]few fixes for list_vm / list_templates
  wrapanapi/msazure.py
Labels: lint-ok

#218 [RFR] openshift client version freeze
  requirements.txt
Labels: lint-ok

#216 Change disk.owner_id to disk.managed_by as per latest azure sdk
  wrapanapi/msazure.py
Labels: bug, lint-ok

#219 [RFR] consistently use absolute imports
  setup.py
  tests/test_hawkular.py
  tests/test_openshift.py
  tests/test_openstack.py
  tests/test_scvmm.py
  tests/test_virtualcenter.py
  wrapanapi/__init__.py
  wrapanapi/base.py
  wrapanapi/containers/__init__.py
  wrapanapi/containers/container.py
  wrapanapi/containers/deployment_config.py
  wrapanapi/containers/image.py
  wrapanapi/containers/image_registry.py
  wrapanapi/containers/node.py
  wrapanapi/containers/pod.py
  wrapanapi/containers/project.py
  wrapanapi/containers/providers/rhkubernetes.py
  wrapanapi/containers/providers/rhopenshift.py
  wrapanapi/containers/replicator.py
  wrapanapi/containers/route.py
  wrapanapi/containers/service.py
  wrapanapi/containers/template.py
  wrapanapi/containers/volume.py
  wrapanapi/ec2.py
  wrapanapi/google.py
  wrapanapi/hawkular.py
  wrapanapi/lenovo.py
  wrapanapi/msazure.py
  wrapanapi/nuage.py
  wrapanapi/openstack.py
  wrapanapi/openstack_infra.py
  wrapanapi/rest_client.py
  wrapanapi/rhevm.py
  wrapanapi/scvmm.py
  wrapanapi/utils/__init__.py
  wrapanapi/utils/json_utils.py
  wrapanapi/vcloud.py
  wrapanapi/virtualcenter.py
  wrapanapi/websocket_client.py
Labels: lint-ok

#220 [RFR] use six to ensure correct python3 imports of urllib functions
  requirements.txt
  tests/test_hawkular.py
  wrapanapi/hawkular.py
Labels: enhancement, lint-ok

#222 [RFR] added missing methods which are required by sprout
  wrapanapi/containers/providers/rhopenshift.py
Labels: lint-ok

#225 [RFR] enable testing on python3 - python3 support is still incomplete
  .gitignore
  .travis.yml
  requirements-test.txt
  requirements.txt
  tests/test_scvmm.py
  tox.ini
  wrapanapi/hawkular.py
  wrapanapi/rhevm.py
Labels: lint-ok

#221 [1LP][RFR] Better error handling for stack_exist() method in ec2.py
  wrapanapi/ec2.py
Labels: enhancement, lint-ok

#224 [RFR] Fixed port accessibility for Lenovo
  wrapanapi/lenovo.py
Labels: enhancement, lint-ok

#226 [RFR] Remove snapshots from unused blobs
  wrapanapi/msazure.py
Labels: bug
