Repository RedHatQE/wrapanapi, pull requests merged in 2018-08, with the labels that each got.

#319 [RFR] fix for serialization issue
  wrapanapi/systems/container/rhopenshift.py
Labels: bug, lint-ok

#320 [RFR] Add tag methods for ec2 instances/images
  tests/test_vm_and_template_systems.py
  wrapanapi/systems/ec2.py
Labels: enhancement, lint-ok

#308 [RFR] fix NoneType in LenovoSystem
  wrapanapi/systems/lenovo.py
Labels: lint-ok

#321 Use getattr for ec2 name
  wrapanapi/systems/ec2.py
Labels: bug, lint-ok

#296 [RFR] Implement list tenants and routers
  wrapanapi/systems/nuage.py
Labels: enhancement, lint-ok

#312 [RFR] Make ip property return IPv4 address (RHV)
  wrapanapi/systems/rhevm.py
Labels: RHV, enhancement, lint-ok

#276 [1LP][RFR]fix for creating floating ip method
  wrapanapi/systems/openstack.py
Labels: bug, lint-ok

#322 [1LP][RFR] new methods necessary for pod ansible deployment test
  wrapanapi/systems/container/rhopenshift.py
Labels: enhancement, lint-ok

#300 Add initial support for Redfish physical provider
  wrapanapi/__init__.py
  wrapanapi/systems/__init__.py
  wrapanapi/systems/redfish.py
Labels: RedFish, lint-ok

#324 [RFR] fix of external ip extract method for quick environments
  wrapanapi/systems/container/rhopenshift.py
Labels: bug, lint-ok

#325 [RFR] Port Nuage System to wrapanapi v3 format
  wrapanapi/systems/nuage.py
Labels: Nuage, bug, lint-ok

#329 [RFR] Fix ensure_state fail when VM is in starting state
  wrapanapi/entities/vm.py
Labels: RHV, bug, lint-ok

#314 [RFR] Add creating of security group ports.
  wrapanapi/systems/msazure.py
Labels: Azure, enhancement, lint-ok

#330 [RFR] openstack infra auth via keystone session
  wrapanapi/systems/openstack_infra.py
Labels: bug, lint-ok
