Repository RedHatQE/wrapanapi, pull requests merged in 2018-04, with the labels that each got.

#241 [RFR] Handle empty response in Nuage API calls
  wrapanapi/nuage.py
Labels: WIP, lint-ok

#243 [RFR] deployment support of 5.8 templates
  wrapanapi/containers/providers/rhopenshift.py
Labels: enhancement, lint-ok

#238 [1LP][RFR] Added delete_file_from_bucket & delete_image to GoogleCloudSystem
  wrapanapi/google.py
Labels: enhancement, lint-ok

#246 [1LP][RFR] Remove need to pin python-novaclient with s/HTTPClient/SessionClient
  requirements.txt
  wrapanapi/openstack.py
  wrapanapi/openstack_infra.py
Labels: bug, lint-ok

#245 [1LP][RFR]fix for get_ip_address
  wrapanapi/msazure.py
Labels: bug, lint-ok
