Repository RedHatQE/wrapanapi, pull requests merged in 2018-07, with the labels that each got.

#287 [1LP][RFR] fixed issue when scc data was overwritten by simultaneously running updates
  wrapanapi/systems/container/rhopenshift.py
Labels: lint-ok

#280 [RFR] Update containers rhopenshift list_image_id to return unique list of image ids
  wrapanapi/systems/container/rhopenshift.py
Labels: lint-ok

#290 [RFR] More wrapanapi 3.x test fixes
  wrapanapi/systems/msazure.py
  wrapanapi/systems/openstack.py
  wrapanapi/systems/scvmm.py
  wrapanapi/systems/virtualcenter.py
Labels: WIP, lint-ok

#291 Tweaks for a couple azure issues
  wrapanapi/systems/msazure.py
Labels: lint-ok

#298 [RFR] Update containers rhopenshift openshift list_image_registry to return only registry name
  wrapanapi/systems/container/rhopenshift.py
Labels: enhancement, lint-ok

#288 [1LP][RFR] refactor lenovo system
  wrapanapi/systems/lenovo.py
Labels: lint-ok

#285 [RFR] initial support of saving config map with urls within project
  wrapanapi/systems/container/rhopenshift.py
Labels: enhancement, lint-ok

#305 Change from mfalesni to mshriver for pypi deploy
  .travis.yml
Labels: bug, lint-ok

#306 working password for mshriver auto-deploy
  .travis.yml
Labels: lint-ok

#309 Refresh azure instance before property fetch
  wrapanapi/systems/ec2.py
  wrapanapi/systems/google.py
  wrapanapi/systems/msazure.py
  wrapanapi/systems/openstack.py
  wrapanapi/systems/rhevm.py
  wrapanapi/systems/scvmm.py
Labels: bug, lint-ok

#310 [RFR] Update ec2 name attribute
  wrapanapi/systems/ec2.py
Labels: bug, lint-ok

#264 [1LP][RFR] Update rhevm, openstack nic and template functions
  requirements.txt
  wrapanapi/systems/ec2.py
  wrapanapi/systems/openstack.py
  wrapanapi/systems/rhevm.py
  wrapanapi/systems/scvmm.py
  wrapanapi/systems/virtualcenter.py
Labels: bug, enhancement, lint-ok

#316 [WIP] adding some mappings list_vm->list_vms, list_template->list_templates
  wrapanapi/systems/container/rhopenshift.py
Labels: enhancement

#315 [RFR] Changing way to create the ssl context as TLSv1.0 is disabled by VMware for vSphere 6.7
  wrapanapi/systems/virtualcenter.py
Labels: bug, lint-ok
