Repository RedHatQE/wrapanapi, pull requests merged in 2018-06, with the labels that each got.

#265 [1LP][RFR] better appliance version handling in openshift
  wrapanapi/containers/providers/rhopenshift.py
Labels: enhancement, lint-ok

#267 [RFR] Fix build - fixes google api and sorts out latent issues
  requirements.txt
  setup.cfg
  tox.ini
  wrapanapi/google.py
Labels: bug, lint-ok

#270 [RFR] Winrm ssl
  wrapanapi/scvmm.py
Labels: lint-ok

#271 Fix rhevm.get_storage_domain_connections
  wrapanapi/rhevm.py
Labels: bug

#272 Fix rhevm storage_domains reference
  wrapanapi/rhevm.py
Labels: bug, lint-ok

#274 [RFR] 2 min sometimes isn't enough to delete vm
  wrapanapi/containers/providers/rhopenshift.py
Labels: enhancement, lint-ok

#273 [1LP] Update RHEVMSystem ovirtsdk4 use
  wrapanapi/rhevm.py
Labels: bug, enhancement, lint-ok

#275 [RFR] Use domain account when enabling guest services
  wrapanapi/scvmm.py
Labels: bug, lint-ok

#259 [RFR] make wrapanapi->openshift use latest openshift client
  wrapanapi/containers/providers/rhopenshift.py
Labels: lint-ok

#255 [1LP][RFR] replacing old openshift api with new one
  README.rst
  tests/test_openshift.py
  wrapanapi/__init__.py
  wrapanapi/containers/__init__.py
  wrapanapi/containers/container.py
  wrapanapi/containers/deployment_config.py
  wrapanapi/containers/image.py
  wrapanapi/containers/image_registry.py
  wrapanapi/containers/node.py
  wrapanapi/containers/pod.py
  wrapanapi/containers/project.py
  wrapanapi/containers/providers/rhkubernetes.py
  wrapanapi/containers/providers/rhopenshift.py
  wrapanapi/containers/replicator.py
  wrapanapi/containers/route.py
  wrapanapi/containers/service.py
  wrapanapi/containers/template.py
  wrapanapi/containers/volume.py
Labels: enhancement, lint-ok

#277 [RFR] increase default wait_for values for openshift
  wrapanapi/containers/providers/rhopenshift.py
Labels: bug, lint-ok

#278 [RFR] replace sprout's regexps with miq_version
  requirements.txt
  wrapanapi/containers/providers/rhopenshift.py
Labels: WIP-testing, lint-ok

#281 [RFR] Bugfix: Call get_vm() in does_vm_exist()
  wrapanapi/entities/vm.py
Labels: bug

#282 [RFR] Don't overwrite class var
  wrapanapi/entities/vm.py
  wrapanapi/systems/base.py
Labels: bug, lint-ok

#283 [RFR] Increase gce delete timeout, change the logic in vm.exists so we don't query for VM twice
  wrapanapi/entities/vm.py
  wrapanapi/systems/google.py
Labels: lint-ok

#284 Handle ManageObjectNotFound in vcenter on object filter
  wrapanapi/systems/virtualcenter.py
Labels: bug, lint-ok
