Repository RedHatQE/wrapanapi, pull requests merged in 2018-12, with the labels that each got.

#347 [RFR] stopping pods hung if their pvs are removed earlier than pods itself
  wrapanapi/systems/container/rhopenshift.py
Labels: Openshift, bug

#345 [RFR]This PR will add `list_s3_bucket` method and forcefully remove the Bucket.
  wrapanapi/systems/ec2.py
Labels: enhancement

#348 [RFR] remove broken vms in openshift
  wrapanapi/systems/container/rhopenshift.py
Labels: bug

#350 [RFR] two new methods for sprout
  wrapanapi/systems/container/rhopenshift.py
Labels: enhancement
