Repository RedHatQE/wrapanapi, pull requests merged in 2019-03, with the labels that each got.

#363 [RFR] Update gce, set service_account type by default
  wrapanapi/systems/google.py
Labels: WIP-testing, enhancement, lint-ok

#366 Update travis config to skip existing deployments
  .travis.yml
Labels: enhancement

#367 [RFR] decoding and parsing ecr creds
  wrapanapi/systems/ec2.py
Labels: enhancement, lint-ok

#361 [RFR] Add in some methods to get the vnic_profiles on system, vm, template
  wrapanapi/systems/rhevm.py
Labels: RHV, enhancement, lint-ok

#369 [RFR]Fixed Typo
  wrapanapi/systems/ec2.py
Labels: bug

#365 [RFR][VirtualCenter] Added method set hot add for cpu and memory
  wrapanapi/exceptions.py
  wrapanapi/systems/virtualcenter.py
Labels: enhancement, lint-ok
