Repository RedHatQE/wrapanapi, pull requests merged in 2019-09, with the labels that each got.

#410 [RFR]: Add a check to make sure the datastore-cluster has datastores on it
  wrapanapi/systems/virtualcenter.py
Labels: VMWare, bug, lint-ok

#407 [1LP][RFR] Added functinality to create vm folder in virtualcenter
  wrapanapi/systems/virtualcenter.py
Labels: lint-ok

#388 [RFR] Added network entity and supporting methods for EC2
  wrapanapi/entities/__init__.py
  wrapanapi/entities/network.py
  wrapanapi/exceptions.py
  wrapanapi/systems/ec2.py
Labels: Amazon, enhancement, lint-ok

#411 [RFR] Add support for zip files
  wrapanapi/systems/scvmm.py
Labels: SCVMM, lint-ok

#409 [RFR] default turn off cache_discovery for gce
  wrapanapi/systems/google.py
Labels: Google, enhancement, lint-ok

#406 [RFR]Adding installation section to enhance README.md
  README.rst
Labels: lint-ok

#412 Move to py3.7
  .travis.yml
  requirements-test.txt
  requirements.txt
  setup.cfg
  setup.py
  tests/test_hawkular.py
  tox.ini
  wrapanapi/__init__.py
  wrapanapi/clients/__init__.py
  wrapanapi/clients/rest_client.py
  wrapanapi/clients/websocket_client.py
  wrapanapi/entities/__init__.py
  wrapanapi/entities/base.py
  wrapanapi/entities/instance.py
  wrapanapi/entities/network.py
  wrapanapi/entities/physical_container.py
  wrapanapi/entities/server.py
  wrapanapi/entities/stack.py
  wrapanapi/entities/template.py
  wrapanapi/entities/vm.py
  wrapanapi/systems/__init__.py
  wrapanapi/systems/base.py
  wrapanapi/systems/container/__init__.py
  wrapanapi/systems/container/rhopenshift.py
  wrapanapi/systems/ec2.py
  wrapanapi/systems/google.py
  wrapanapi/systems/hawkular.py
  wrapanapi/systems/lenovo.py
  wrapanapi/systems/msazure.py
  wrapanapi/systems/nuage.py
  wrapanapi/systems/openstack.py
  wrapanapi/systems/openstack_infra.py
  wrapanapi/systems/redfish.py
  wrapanapi/systems/rhevm.py
  wrapanapi/systems/scvmm.py
  wrapanapi/systems/vcloud.py
  wrapanapi/systems/virtualcenter.py
  wrapanapi/utils/__init__.py
  wrapanapi/utils/json_utils.py
Labels: enhancement, lint-ok, python3

#414 [RFR] replacing num_sec with timeout
  wrapanapi/systems/container/rhopenshift.py
Labels: enhancement, lint-ok

#413 [1LP][WIPTEST] Added get_quota method
  wrapanapi/systems/openstack.py
Labels: WIP-testing, enhancement, lint-ok

#418 [RFR] Allow for unzipping archive on Powershell 4
  wrapanapi/systems/scvmm.py
Labels: SCVMM, bug, lint-ok

#415 [1LP][RFR]SharedMethodMixin for EC2 implemented
  wrapanapi/systems/ec2.py
Labels: Amazon, enhancement, lint-ok

#416 [RFR]_get_resource method implemented for EC2System
  wrapanapi/systems/ec2.py
Labels: Amazon, enhancement, lint-ok

#419 [1LP][RFR] Azure iot client, create/add iothub
  wrapanapi/systems/msazure.py
Labels: Azure, enhancement, lint-ok
