Repository RedHatQE/wrapanapi, pull requests merged in 2019-01, with the labels that each got.

#352 [RFR] supplementary methods for pod appliance testing
  wrapanapi/systems/container/rhopenshift.py
Labels: Openshift, enhancement

#351 [RFR] wrongly updated method during wrapanapi 3.0 conversion
  wrapanapi/systems/rhevm.py
  wrapanapi/systems/scvmm.py
Labels: bug

#356 [1LP][RFR] adding template params to deploy_template
  wrapanapi/systems/container/rhopenshift.py
Labels: enhancement

#355 async as reserved keyworkd in py3.7+
  requirements.txt
  wrapanapi/systems/rhevm.py
Labels: enhancement, lint-ok

#353 [RFR] added disc delete in the vm cleanup
  wrapanapi/systems/msazure.py
Labels: Azure, bug, lint-ok
