Repository RedHatQE/wrapanapi, pull requests merged in 2019-06, with the labels that each got.

#384 [1LP][RFR] Add in function for listing VHDs present in SCVMM library
  wrapanapi/systems/scvmm.py
Labels: enhancement, lint-ok

#385 [1LP][RFR] Adding SharedMethodsMixin class
  wrapanapi/systems/openstack.py
  wrapanapi/systems/rhevm.py
Labels: enhancement, lint-ok

#386 [1LP][RFR] Add all_ips method to VM entities
  wrapanapi/entities/vm.py
  wrapanapi/systems/ec2.py
  wrapanapi/systems/google.py
  wrapanapi/systems/msazure.py
  wrapanapi/systems/openstack.py
  wrapanapi/systems/rhevm.py
  wrapanapi/systems/scvmm.py
  wrapanapi/systems/virtualcenter.py
Labels: Amazon, Azure, Openstack, RHV, SCVMM, VMWare, WIP, enhancement, lint-ok

#391 [RFR] Fix reference before assignment in rhevm VM.mark_as_template
  wrapanapi/systems/rhevm.py
Labels: RHV, bug, lint-ok

#390 [1LP][RFR] Update rhevm add_disk kwargs
  wrapanapi/systems/rhevm.py
Labels: RHV, enhancement, lint-ok

#392 [RFR]EC2Instance change instance type method
  wrapanapi/systems/ec2.py
Labels: Amazon, enhancement, lint-ok

#393 [RFR] Modify the Redfish resources' name
  wrapanapi/systems/redfish.py
Labels: RedFish, enhancement, lint-ok

#377 [RFR] scvmm py3 support
  requirements.txt
Labels: lint-ok, python3

#394 [RFR] Change list_hosts to list_host
  wrapanapi/systems/openstack_infra.py
  wrapanapi/systems/scvmm.py
Labels: Openstack, SCVMM, bug, lint-ok
