Repository RedHatQE/wrapanapi, pull requests merged in 2019-04, with the labels that each got.

#372 [RFR] Fix issue with deleting a SCVMM vm by removing Force kwarg
  wrapanapi/systems/scvmm.py
Labels: SCVMM, bug, lint-ok

#362 [1LP][RFR] ec2.py module changed from boto to boto3
  wrapanapi/systems/ec2.py
Labels: enhancement, lint-ok, python3

#364 [1LP][RFR] RHEVM updates for template upload
  wrapanapi/systems/rhevm.py
Labels: RHV, enhancement, lint-ok

#360 [1LP][RFR] Openstack: swift manger container and obj management
  requirements.txt
  wrapanapi/systems/openstack.py
Labels: Openstack, enhancement, lint-ok

#373 [RFR]Adding new method for listing disks on RHV
  wrapanapi/systems/rhevm.py
Labels: RHV, enhancement, lint-ok

#368 [RFR] Add Support For Datastore Clusters for Vmware
  wrapanapi/exceptions.py
  wrapanapi/systems/virtualcenter.py
Labels: VMWare, enhancement, lint-ok

#375 Fix TypeError when listing IPs in rhv 4.3
  wrapanapi/systems/rhevm.py
Labels: bug, lint-ok

#374 [RFR] Add ability to create a snapshot for SCVirtualMachine
  wrapanapi/systems/scvmm.py
Labels: SCVMM, enhancement, lint-ok

#370 [RFR] Fixes required for test_provision_with_boot_volume
  wrapanapi/systems/openstack.py
Labels: Openstack, enhancement, lint-ok
