Repository RedHatQE/wrapanapi, pull requests merged in 2020-04, with the labels that each got.

#442 Set azure meta package version to <5.0.0
  setup.cfg
Labels: Azure

#439 [RFR]get_template should also check public images
  wrapanapi/systems/ec2.py
Labels: Amazon

#440 [RFR]Added register_image method for EC2System
  wrapanapi/systems/ec2.py
Labels: Amazon, enhancement
