Repository RedHatQE/wrapanapi, pull requests merged in 2020-02, with the labels that each got.

#436 Adding new method to unregister vm from vmware
  wrapanapi/systems/virtualcenter.py
Labels: VMWare, enhancement

#434 [RFR]Added ec2 snapshot import functions
  wrapanapi/systems/ec2.py
Labels: Amazon, enhancement, lint-ok

#435 [RFR]List routers/subnets that have tags and don't have Name tag
  wrapanapi/systems/ec2.py
Labels: Amazon, bug
